spring.application.name=DAT108-Oblig4-Gr4

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com:5433/h186506
spring.datasource.username=h186506
spring.datasource.password=#37?3fJoc&YCXfkF

spring.jpa.open-in-view=true